export const skeletone = [
  {
    plan: {
      name: "New Veh",
      small: "(Sale since 1st Apr23 BS6)",
      rowSpan: 2,
      css: "blue400",
      tdcss: "cell",
      id: "new-veh",
    },
    total: 0,
    Buses: 0,
    HCV: 0,
    ILMCV: 0,
    Yodha_Ace_EV: 0,
    Magic_Winger: 0,
  },
  {
    plan: {
      css: "blue400",
      tdcss: "cell",
    },
    total: "0%",
    Buses: 0,
    HCV: 0,
    ILMCV: 0,
    Yodha_Ace_EV: 0,
    Magic_Winger: 0,
  },
  {
    plan: {
      name: "+ standard",
      rowSpan: 2,
      onclick: "standard",
      css: "blue200",
      tdcss: "cell",
      id: "std-prt",
      class: "std-prt",
    },
    total: 0,
    Buses: 0,
    HCV: 0,
    ILMCV: 0,
    Yodha_Ace_EV: 0,
    Magic_Winger: 0,
  },
  {
    plan: {
      css: "blue200",
      tdcss: "cell",
      id: "std-prt",
      class: "std-prt",
    },
    total: "0%",
    Buses: 0,
    HCV: 0,
    ILMCV: 0,
    Yodha_Ace_EV: 0,
    Magic_Winger: 0,
  },
  {
    plan: {
      name: "1Y",
      rowSpan: 2,
      css: "slate100",
      tdcss: "cell",
      id: "std-chd",
      class: "std-chd",
    },
    total: 0,
    Buses: 0,
    HCV: 0,
    ILMCV: 0,
    Yodha_Ace_EV: 0,
    Magic_Winger: 0,
  },
  {
    plan: {
      css: "slate100",
      tdcss: "cell",
      id: "std-chd",
      class: "std-chd",
    },
    total: "0%",
    Buses: 0,
    HCV: 0,
    ILMCV: 0,
    Yodha_Ace_EV: 0,
    Magic_Winger: 0,
  },
  {
    plan: {
      name: "2Y",
      rowSpan: 2,
      css: "slate100",
      tdcss: "cell",
      id: "std-chd",
      class: "std-chd",
    },
    total: 0,
    Buses: 0,
    HCV: 0,
    ILMCV: 0,
    Yodha_Ace_EV: 0,
    Magic_Winger: 0,
  },
  {
    plan: {
      css: "slate100",
      tdcss: "cell",
      id: "std-chd",
      class: "std-chd",
    },
    total: "0%",
    Buses: 0,
    HCV: 0,
    ILMCV: 0,
    Yodha_Ace_EV: 0,
    Magic_Winger: 0,
  },
  {
    plan: {
      name: "3Y",
      rowSpan: 2,
      css: "slate100",
      tdcss: "cell",
      id: "std-chd",
      class: "std-chd",
    },
    total: 0,
    Buses: 0,
    HCV: 0,
    ILMCV: 0,
    Yodha_Ace_EV: 0,
    Magic_Winger: 0,
  },
  {
    plan: {
      css: "slate100",
      tdcss: "cell",
      id: "std-chd",
      class: "std-chd",
    },
    total: "0%",
    Buses: 0,
    HCV: 0,
    ILMCV: 0,
    Yodha_Ace_EV: 0,
    Magic_Winger: 0,
  },
  {
    plan: {
      name: "+ Advance",
      rowSpan: 2,
      onclick: "advance",
      css: "blue200",
      tdcss: "cell",
      class: "adv-prt",
      id: "adv-prt",
    },
    total: 0,
    Buses: 0,
    HCV: 0,
    ILMCV: 0,
    Yodha_Ace_EV: 0,
    Magic_Winger: 0,
  },
  {
    plan: {
      css: "blue200",
      tdcss: "cell",
      class: "adv-prt",
      id: "adv-prt",
    },
    total: "0%",
    Buses: 0,
    HCV: 0,
    ILMCV: 0,
    Yodha_Ace_EV: 0,
    Magic_Winger: 0,
  },
  {
    plan: {
      name: "Full-Purchase",
      rowSpan: 2,
      css: "slate300",
      tdcss: "cell",
      id: "fp-prt",
      class: "adv-chd",
    },
    total: 0,
    Buses: 0,
    HCV: 0,
    ILMCV: 0,
    Yodha_Ace_EV: 0,
    Magic_Winger: 0,
  },
  {
    plan: {
      css: "slate300",
      tdcss: "cell",
      id: "fp-prt",
      class: "adv-chd",
    },
    total: "0%",
    Buses: 0,
    HCV: 0,
    ILMCV: 0,
    Yodha_Ace_EV: 0,
    Magic_Winger: 0,
  },
  {
    plan: {
      name: "1Y",
      rowSpan: 2,
      css: "slate100",
      tdcss: "cell",
      class: "adv-chd",
      id: "fp-chd",
    },
    total: 0,
    Buses: 0,
    HCV: 0,
    ILMCV: 0,
    Yodha_Ace_EV: 0,
    Magic_Winger: 0,
  },
  {
    plan: {
      css: "slate100",
      tdcss: "cell",
      class: "adv-chd",
      id: "fp-chd",
    },
    total: "0%",
    Buses: 0,
    HCV: 0,
    ILMCV: 0,
    Yodha_Ace_EV: 0,
    Magic_Winger: 0,
  },
  {
    plan: {
      name: "2Y",
      rowSpan: 2,
      css: "slate100",
      tdcss: "cell",
      class: "adv-chd",
      id: "fp-chd",
    },
    total: 0,
    Buses: 0,
    HCV: 0,
    ILMCV: 0,
    Yodha_Ace_EV: 0,
    Magic_Winger: 0,
  },
  {
    plan: {
      css: "slate100",
      tdcss: "cell",
      class: "adv-chd",
      id: "fp-chd",
    },
    total: "0%",
    Buses: 0,
    HCV: 0,
    ILMCV: 0,
    Yodha_Ace_EV: 0,
    Magic_Winger: 0,
  },
  {
    plan: {
      name: "3Y",
      rowSpan: 2,
      css: "slate100",
      tdcss: "cell",
      class: "adv-chd",
      id: "fp-chd",
    },
    total: 0,
    Buses: 0,
    HCV: 0,
    ILMCV: 0,
    Yodha_Ace_EV: 0,
    Magic_Winger: 0,
  },
  {
    plan: {
      css: "slate100",
      tdcss: "cell",
      class: "adv-chd",
      id: "fp-chd",
    },
    total: "0%",
    Buses: 0,
    HCV: 0,
    ILMCV: 0,
    Yodha_Ace_EV: 0,
    Magic_Winger: 0,
  },
  {
    plan: {
      name: "Upgrade",
      rowSpan: 2,
      css: "slate300",
      tdcss: "cell",
      class: "adv-chd",
      id: "up-prt",
    },
    total: 0,
    Buses: 0,
    HCV: 0,
    ILMCV: 0,
    Yodha_Ace_EV: 0,
    Magic_Winger: 0,
  },
  {
    plan: {
      css: "slate300",
      tdcss: "cell",
      class: "adv-chd",
    },
    total: "0%",
    Buses: 0,
    HCV: 0,
    ILMCV: 0,
    Yodha_Ace_EV: 0,
    Magic_Winger: 0,
  },
  {
    plan: {
      name: "1Y",
      rowSpan: 2,
      css: "slate100",
      tdcss: "cell",
      class: "adv-chd",
      id: "up-chd",
    },
    total: 0,
    Buses: 0,
    HCV: 0,
    ILMCV: 0,
    Yodha_Ace_EV: 0,
    Magic_Winger: 0,
  },
  {
    plan: {
      css: "slate100",
      tdcss: "cell",
      class: "adv-chd",
      id: "up-chd",
    },
    total: "0%",
    Buses: 0,
    HCV: 0,
    ILMCV: 0,
    Yodha_Ace_EV: 0,
    Magic_Winger: 0,
  },
  {
    plan: {
      name: "2Y",
      rowSpan: 2,
      css: "slate100",
      tdcss: "cell",
      class: "adv-chd",
      id: "up-chd",
    },
    total: 0,
    Buses: 0,
    HCV: 0,
    ILMCV: 0,
    Yodha_Ace_EV: 0,
    Magic_Winger: 0,
  },
  {
    plan: {
      css: "slate100",
      tdcss: "cell",
      class: "adv-chd",
      id: "up-chd",
    },
    total: "0%",
    Buses: 0,
    HCV: 0,
    ILMCV: 0,
    Yodha_Ace_EV: 0,
    Magic_Winger: 0,
  },
  {
    plan: {
      name: "3Y",
      rowSpan: 2,
      css: "slate100",
      tdcss: "cell",
      class: "adv-chd",
      id: "up-chd",
    },
    total: 0,
    Buses: 0,
    HCV: 0,
    ILMCV: 0,
    Yodha_Ace_EV: 0,
    Magic_Winger: 0,
  },
  {
    plan: {
      css: "slate100",
      tdcss: "cell",
      class: "adv-chd",
      id: "up-chd",
    },
    total: "0%",
    Buses: 0,
    HCV: 0,
    ILMCV: 0,
    Yodha_Ace_EV: 0,
    Magic_Winger: 0,
  },
  {
    plan: {
      name: "Grand Total (New+Existing)",
      rowSpan: 2,
      css: "blue400",
      tdcss: "cell",
      id: "grand-total",
    },
    total: 0,
    Buses: 0,
    HCV: 0,
    ILMCV: 0,
    Yodha_Ace_EV: 0,
    Magic_Winger: 0,
  },
  {
    plan: {
      css: "blue400",
      tdcss: "cell",
    },
    total: "0%",
    Buses: 0,
    HCV: 0,
    ILMCV: 0,
    Yodha_Ace_EV: 0,
    Magic_Winger: 0,
  },
];
